ktor:
  application:
    modules:
      - ru.tochoz.ApplicationKt.module
  deployment:
#    watch:
#      - classes
#      - resources
    port: "$PORT:8080"
#    development: true
postgres:
  embededMode: false
  url: "$PG_QUEENS_URL:'localhost:5432/guest'"
  user: "$PG_QUEENS_USER:guest"
  password: "$PG_QUEENS_PASSWD:guest"